# Generated by Django 2.1.2 on 2018-10-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
